### ISSUE TITLE
Fail to use getHeaders on request.response from Pipe

### ISSUE THREAD

**Issue by BaptisteKaliop** [kuzzleio/kuzzle-common-objects#27]
I used these events  : 
- request:onSuccess
- request:onError
- request:onUnauthorized

that I linked to a specific function that handle HTTP headers.

I try to read the headers that are in the response with the function that is specified in the documentation : 
https://github.com/kuzzleio/kuzzle-common-objects#getheaders

```
this.outputRequestSetHeaders = function(request, callback) {
        console.log(request.response.getHeaders());
        return callback(null, request);
    };
```

And I have the following error in pm2 logs : 
```
TypeError: request.response.getHeaders is not a function
```

Looking at : https://github.com/kuzzleio/kuzzle-common-objects/blob/master/lib/models/requestResponse.js

There is no getHeaders function

**Comment by ballinette** [comment]
Hi @BaptisteKaliop 
The doc is wrong, you can get the headers with `request.response.headers`

**Comment by BaptisteKaliop** [comment]
hi @ballinette 

Thanks for the quick answer :)
